sudo: required
services: 
  - docker

before_install:
  - docker build -t rushikeshpharate/docker-react-first -f Dockerfile.dev .

script:
  - docker run -e CI=true rushikeshpharate/docker-react-first npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-first"
  env: "Dockerreactfirst-env"
  bucket_name: "elasticbeanstalk-us-east-2-799916083261"
  bucket_path: "docker-react-first"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
