sudo: required
services: 
  - docker

before_install:
  - docker build -t rushikeshpharate/docker-react-first -f Dockerfile.dev .

script:
  - docker run -e CI=true rushikeshpharate/docker-react-first npm run test 

